#!/bin/bash

BERSONALBASE_PTAH=/root/BersonalBase/manage.py

do_start()
{
    nohup python3 $BERSONALBASE_PTAH >  /dev/null 2>&1 &
}

do_stop()
{
    pkill -f $BERSONALBASE_PTAH
}

do_restart()
{
    do_stop
    sleep 1
    do_start
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    status)
        exit $?
        ;;
    reload)
        echo "reload"
        ;;
    restart)
        do_restart
        ;;
    *)
        echo "Usage: {start|stop|restart|reload}" >&2
        exit 3
        ;;
esac
exit 0
